_BASE_: "Base-RCNN-DilatedC5.yaml"
MODEL:
  WEIGHTS: "models/DRN-WSOD/resnet18_ws_model_120_d2.pkl"
  BACKBONE:
    NAME: "build_wsl_resnet_backbone"
    FREEZE_AT: 5
  RESNETS:
    DEPTH: 18
    RES5_DILATION: 2
    RES2_OUT_CHANNELS: 64
    OUT_FEATURES: ["res5"]
  ANCHOR_GENERATOR:
    SIZES: [32, 64, 128, 256, 512, 768]
    ASPECT_RATIOS: [[1.0, 2.0, 0.5]]
  ROI_HEADS:
    IN_FEATURES: ["res5"]
SOLVER:
  STEPS: (140000,)
  MAX_ITER: 200000
  WARMUP_ITERS: 200
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 2.0
  WEIGHT_DECAY_BIAS: 0.0
