# -*- coding: utf-8 -*-
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved

from detectron2.config import CfgNode as CN


def add_wsovod_config(cfg):
    """
    Add config for wsovod.
    """
    _C = cfg
    _C.WSOVOD = CN()
    _C.WSOVOD.ITER_SIZE = 1
    _C.WSOVOD.CLS_AGNOSTIC_BBOX_KNOWN = False
    _C.WSOVOD.SAMPLING = CN()
    _C.WSOVOD.SAMPLING.SAMPLING_ON = False
    _C.WSOVOD.SAMPLING.IOU_THRESHOLDS = [[0.5], [0.5], [0.5], [0.5]]
    _C.WSOVOD.SAMPLING.IOU_LABELS = [[0, 1], [0, 1], [0, 1], [0, 1]]
    _C.WSOVOD.SAMPLING.BATCH_SIZE_PER_IMAGE = [4096, 4096, 4096, 4096]
    _C.WSOVOD.SAMPLING.POSITIVE_FRACTION = [1.0, 1.0, 1.0, 1.0]
    _C.WSOVOD.OBJECT_MINING = CN()
    _C.WSOVOD.OBJECT_MINING.WEIGHT = 1.0
    _C.WSOVOD.OBJECT_MINING.MEAN_LOSS = True
    _C.WSOVOD.INSTANCE_REFINEMENT = CN()
    _C.WSOVOD.INSTANCE_REFINEMENT.WEIGHT = 1.0
    _C.WSOVOD.INSTANCE_REFINEMENT.REFINE_NUM = 3
    _C.WSOVOD.INSTANCE_REFINEMENT.REFINE_REG = [False, False, False]
    _C.WSOVOD.INSTANCE_REFINEMENT.REFINE_MIST = False
    _C.WSOVOD.INSTANCE_REFINEMENT.CROSS_ENTROPY_WEIGHTED = True
    _C.WSOVOD.BBOX_REFINE = CN()
    _C.WSOVOD.BBOX_REFINE.ENABLE = False
    _C.WSOVOD.BBOX_REFINE.MODEL_TYPE = "vit_b" # vit_h vit_l vit_b
    _C.WSOVOD.BBOX_REFINE.MODEL_CHECKPOINT = "tools/sam_checkpoints/sam_vit_b_01ec64.pth" # sam_checkpoints/sam_vit_h_4b8939.pth sam_checkpoints/sam_vit_l_0b3195.pth sam_checkpoints/sam_vit_b_01ec64.pth

    # VGG
    _C.MODEL.VGG = CN()
    _C.MODEL.VGG.DEPTH = 16
    _C.MODEL.VGG.OUT_FEATURES = ["plain5"]
    _C.MODEL.VGG.CONV5_DILATION = 1
    # Swin
    _C.MODEL.SWIN = CN()
    _C.MODEL.SWIN.EMBED_DIM = 96
    _C.MODEL.SWIN.OUT_FEATURES = ["stage2", "stage3", "stage4", "stage5"]
    _C.MODEL.SWIN.DEPTHS = [2, 2, 6, 2]
    _C.MODEL.SWIN.NUM_HEADS = [3, 6, 12, 24]
    _C.MODEL.SWIN.WINDOW_SIZE = 7
    _C.MODEL.SWIN.MLP_RATIO = 4
    _C.MODEL.SWIN.DROP_PATH_RATE = 0.2
    _C.MODEL.SWIN.APE = False
    _C.MODEL.SWIN.PATH_NORM = True

    _C.MODEL.ROI_BOX_HEAD.DAN_DIM = [4096, 4096]
    _C.MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY = CN()
    _C.MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.WEIGHT_PATH_TRAIN = ''
    _C.MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.WEIGHT_PATH_TEST = ''
    _C.MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.WEIGHT_DIM = 512
    _C.MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.USE_BIAS = 0.0
    _C.MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.NORM_WEIGHT = True
    _C.MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.NORM_TEMP = 100.0
    _C.MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.DATA_AWARE = False
    _C.MODEL.ROI_BOX_HEAD.OPEN_VOCABULARY.PROTOTYPE_NUM = 5

    _C.MODEL.RPN.SCORE_THRESH_TRAIN = 0.2
    _C.MODEL.RPN.SCORE_THRESH_TEST = 0.2
    _C.MODEL.RPN.TOPK_CANDIDATES_TRAIN = 2000
    _C.MODEL.RPN.TOPK_CANDIDATES_TEST = 1000

    _C.MODEL.MRRP = CN()
    _C.MODEL.MRRP.MRRP_ON = False
    _C.MODEL.MRRP.NUM_BRANCH = 3
    _C.MODEL.MRRP.BRANCH_DILATIONS = [1, 2, 3]
    _C.MODEL.MRRP.MRRP_STAGE = "res4"
    _C.MODEL.MRRP.TEST_BRANCH_IDX = 1    

    _C.DATALOADER.CLASS_ASPECT_RATIO_GROUPING = False

    _C.TEST.EVAL_TRAIN = False
    _C.VIS_TEST = False

    _C.SOLVER.OPTIMIZER = "SGD"
    _C.SOLVER.BACKBONE_MULTIPLIER = 1.0
    _C.SOLVER.BASE_LR_END = 0.1

